# Generated by Django 5.1 on 2024-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='image',
            field=models.ImageField(upload_to='codes/'),
        ),
    ]
